### ISSUE TITLE
lua_shared_dict的一些疑惑

### ISSUE THREAD

**Issue by cylovefree** [LomoX-Offical/openresty-source-code-analysis#1]
您好，看了您的项目，收获非常多，非常感谢！
有一些疑问请求您的解答。
利用nginx的lua模块创建一块共享内存，然后利用get函数可以查找字典对象中的key-value，这样通过一系列的计算可以得到想要的一些信息。这里面创建的共享内存中的字典对象存储的是所有http请求的信息吗？

**Comment by zqzjz0911** [comment]
不是，你想存储什么就存什么

**Comment by cylovefree** [comment]
嗯，我回头仔细看 了一下，闲杂明白了，非常感谢！
